In [1]:
import torch
import scanpy as sc
import pandas as pd
import numpy as np
from typing import Literal
from scib.preprocessing import get_cell_cycle_genes

In [2]:
adata = sc.read_h5ad('../../../oscb/user_storage/Benchmarks/Diabetic-Kidney-Disease_1760540806755/QC/control_1Liger_integration.h5ad')
adata

AnnData object with n_obs × n_vars = 35703 × 2000
    obs: 'orig.ident', 'n_counts', 'n_genes', 'soma_joinid', 'dataset_id', 'assay', 'assay_ontology_term_id', 'cell_type', 'cell_type_ontology_term_id', 'development_stage', 'development_stage_ontology_term_id', 'disease', 'disease_ontology_term_id', 'donor_id', 'is_primary_data', 'self_reported_ethnicity', 'self_reported_ethnicity_ontology_term_id', 'sex', 'sex_ontology_term_id', 'suspension_type', 'tissue', 'tissue_ontology_term_id', 'tissue_general', 'tissue_general_ontology_term_id', 'nFeatures_RNA', 'batch', 'size_factors', 'nFeatures_RNA_by_counts', 'log1p_nFeatures_RNA_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'doublet_score', 'predicted_doublet', 'clf_doublet', 'clf_score', 'leiden', 'louvain', 

In [6]:
adata.obsm['X_inmf'].shape

(35703, 30)

In [6]:
from scib.preprocessing import get_cell_cycle_genes

In [22]:
def has_cell_cyle_genes(
    adata: sc.AnnData, 
    species: Literal[
        "mouse",
        "mus musculus",
        "mus_musculus",
        "human",
        "homo sapiens",
        "homo_sapiens",
        "c_elegans",
        "c elegans",
        "caenorhabditis elegans",
        "caenorhabditis_elegans",
        "zebrafish",
        "danio rerio",
        "danio_rerio",
    ]):
    columns = ["gene_name", "gene_id"]
    gene_map = get_cell_cycle_genes(species)
    df_s = gene_map.query("phase == 'S'")
    df_g = gene_map.query("phase == 'G2/M'")
    
    n_genes_s = 0
    for col in columns:
        _genes = [g for g in df_s[col] if g in adata.var_names]
        if len(_genes) > n_genes_s:  # pick largest overlapping set
            n_genes_s = len(_genes)
            genes_s = _genes
            
    if n_genes_s == 0:
        return False

    n_genes_g = 0
    for col in columns:
        _genes = [g for g in df_g[col] if g in adata.var_names]
        if len(_genes) > n_genes_g:  # pick largest overlapping set
            n_genes_g = len(_genes)
            genes_g = _genes
            
    if n_genes_g == 0:
        return False
        
    return True

In [15]:
# Get gene sets
gene_map = get_cell_cycle_genes("human")
has_cell_cyle_genes(adata, gene_map.query("phase == 'S'"))

False

In [23]:
has_cell_cyle_genes(adata, "human")

False

In [4]:
adata.layers['counts'].todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [2]:
adata1 = sc.read_h5ad('../../../oscb/user_storage/Benchmarks/Diabetic-Kidney-Disease_1760540806755/QC/control_1Seurat_integration.h5ad')
adata1

AnnData object with n_obs × n_vars = 35703 × 1097
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'soma_joinid', 'dataset_id', 'assay', 'assay_ontology_term_id', 'cell_type', 'cell_type_ontology_term_id', 'development_stage', 'development_stage_ontology_term_id', 'disease', 'disease_ontology_term_id', 'donor_id', 'is_primary_data', 'self_reported_ethnicity', 'self_reported_ethnicity_ontology_term_id', 'sex', 'sex_ontology_term_id', 'suspension_type', 'tissue', 'tissue_ontology_term_id', 'tissue_general', 'tissue_general_ontology_term_id', 'nFeatures_RNA', 'batch', 'size_factors', 'nFeatures_RNA_by_counts', 'log1p_nFeatures_RNA_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'doublet_score', 'predicted_doublet', 'clf_doublet', 'clf_score', 'leiden', 'lou

In [5]:
adata1.obsm['RNA_counts'].todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        ...,
        [0., 3., 0., ..., 0., 0., 0.],
        [1., 2., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
adata0 = sc.read_h5ad('../../../oscb/user_storage/Benchmarks/Diabetic-Kidney-Disease_1760540806755/QC/Diabetic_Kidney_Disease_scanpy.h5ad')
adata0

AnnData object with n_obs × n_vars = 39176 × 2000
    obs: 'soma_joinid', 'dataset_id', 'assay', 'assay_ontology_term_id', 'cell_type', 'cell_type_ontology_term_id', 'development_stage', 'development_stage_ontology_term_id', 'disease', 'disease_ontology_term_id', 'donor_id', 'is_primary_data', 'self_reported_ethnicity', 'self_reported_ethnicity_ontology_term_id', 'sex', 'sex_ontology_term_id', 'suspension_type', 'tissue', 'tissue_ontology_term_id', 'tissue_general', 'tissue_general_ontology_term_id', 'n_genes', 'batch', 'size_factors', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'doublet_score', 'predicted_doublet', 'clf_doublet', 'clf_score', 'leiden', 'louvain'
    var: 'soma_joinid', 'feature_id', 'feature_name', 'f

In [13]:
adata1.X.todense()

matrix([[ 0.34866482,  0.74842036,  0.75822645, ...,  0.6139579 ,
          0.15706107,  0.        ],
        [ 0.63411117,  0.89986503,  0.55929047, ...,  1.8990068 ,
          4.270479  ,  0.        ],
        [ 0.6075849 ,  0.55090874,  0.31947243, ..., -0.5722059 ,
          3.7467613 ,  0.        ],
        ...,
        [ 0.        ,  3.2948744 ,  3.2948744 , ...,  0.        ,
          4.368461  ,  0.        ],
        [ 3.575773  ,  0.        ,  0.        , ...,  0.        ,
          4.254824  ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          2.7679136 ,  0.        ]], dtype=float32)

In [4]:
adata.var

,soma_joinid,feature_id,feature_name,feature_length,n_cells,hvg,hvg_score,ensembl_ids,mt,ribo,...,log1p_mean_counts,pct_dropout_by_counts,total_counts,log1p_total_counts,highly_variable,means,dispersions,dispersions_norm,mean,std
gene_symbols,,,,,,,,,,,,,,,,,,,,,
A2M,3,ENSG00000175899,A2M,6318,1491,True,5.759065,ENSG00000175899,False,False,...,0.070629,96.194098,2867.0,7.961370,True,0.187964,2.609882,2.826005,5.208617e-11,0.330396
AADACL2-AS1,14,ENSG00000242908,AADACL2-AS1,635,95,False,2.059569,ENSG00000242908,False,False,...,0.002982,99.757505,117.0,4.770685,True,0.008621,2.141358,1.679032,-1.263523e-11,0.070049
AARD,25,ENSG00000205002,AARD,2404,20,False,1.370114,ENSG00000205002,False,False,...,0.000536,99.948948,21.0,3.091043,True,0.001559,2.087312,1.546725,1.866164e-12,0.029453
AP001053.11,32,ENSG00000215458,AATBC,4874,41,False,2.655243,ENSG00000215458,False,False,...,0.001046,99.895344,41.0,3.737670,True,0.004032,2.057056,1.472657,8.834320e-12,0.048103
ABCA8,48,ENSG00000141338,ABCA8,11246,481,True,4.012566,ENSG00000141338,False,False,...,0.020090,98.772207,795.0,6.679599,True,0.056725,2.524186,2.616217,-1.548797e-11,0.177262
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000287708,60264,ENSG00000287708,RP11-120J1.2,4224,338,False,2.304880,ENSG00000287708,False,False,...,0.015325,99.137227,605.0,6.406880,True,0.031578,2.103961,1.587483,-1.030000e-12,0.135250
ENSG00000287830,60321,ENSG00000287830,RP11-297M9.3,1797,16,False,2.561936,ENSG00000287830,False,False,...,0.000408,99.959159,16.0,2.833213,True,0.001720,2.139521,1.674536,-9.330682e-13,0.031227
ENSG00000287968,60379,ENSG00000287968,RP11-638O6.2,852,5,False,2.219521,ENSG00000287968,False,False,...,0.000128,99.987237,5.0,1.791759,True,0.000481,2.064770,1.491542,-3.369646e-12,0.016538


In [2]:
adata = sc.read_h5ad('../../../oscb/user_storage/Benchmarks/Planaria_1756435730595/planaria-full.h5ad')

In [3]:
adata

AnnData object with n_obs × n_vars = 18837 × 2000
    obs: 'labels'
    var: 'gene_ids', 'gene_symbols', 'feature_types', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'benchmark_traj', 'hvg', 'log1p', 'origin_group'

In [4]:
adata.X

array([[3.754158 , 0.       , 2.8936098, ..., 0.       , 0.       ,
        0.       ],
       [3.6648524, 0.       , 1.0338683, ..., 0.       , 0.       ,
        0.       ],
       [5.5846467, 0.       , 5.121978 , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [4.4665804, 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [7.506142 , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [7.6656914, 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ]], dtype=float32)

In [5]:
sc.pp.pca(adata, svd_solver='arpack', random_state=0)

In [6]:
sc.pp.neighbors(adata, n_neighbors=15, n_pcs=None, random_state=0)

In [7]:
pip install --upgrade numba

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Note: you may need to restart the kernel to use updated packages.
